# Generated by Django 6.1 on 2026-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
