# Generated by Django 6.1 on 2026-09-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promptlog_recipient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptLog',
        ),
    ]
